model:
  TYPE: LT # or OPTREE
  BST_DEPTH: 2
  LINEAR: False
  SPLIT: linear
  COMP: concatenate

training:
  SEED: 2020
  LR: 0.5
  ITER: 1e4
  REG: 0
  TWO_PHASED: True

dataset:
  DISTR: xor # or swissroll
  N: 100 # number of training points