SEED: 2020

model:
  TYPE: LT # or OPTREE
  BST_DEPTH: 2
  LR: 0.5
  ITER: 1e4
  REG: 0
  LINEAR: True
  SPLIT: elu
  COMP: residual

dataset:
  DISTR: xor # or swissroll
  N: 100 # number of training points